### ISSUE TITLE
Two recommendations

### ISSUE THREAD

**Issue by keanfreeman** [sakurazuka90/chultMap#1]
I love this!

1. resetToToAStartState should probably be called by default, I don't think anyone's going to use the map completely blank by default.
2. We should use [localstorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) so the user doesn't have to re-click the tiles when they come back with the same browser.

**Comment by sakurazuka90** [comment]
Thank you for your input!

I added resetting to localstorage state if available, or to start state if not on load. And saving state in local storage on unload.
